"""Constants for the Amaran Sidus integration."""

DOMAIN = "amaran"

DEFAULT_NAME = "Amaran Ace 25C"
MANUFACTURER = "amaran"

CONF_ADDRESS = "address"
CONF_APP_KEY = "app_key"
CONF_BLE_MAC = "ble_mac"
CONF_BATTERY_CAPABLE = "battery_capable"
CONF_BATTERY_PERCENTAGE = "battery_percentage"
CONF_DEVICE_UUID = "device_uuid"
CONF_ENABLE_DISCOVERY = "enable_discovery"
CONF_ENABLE_PRESENCE_CHECKING = "enable_presence_checking"
CONF_FIXTURE_CATALOG = "fixture_catalog"
CONF_FIXTURE_CODE = "fixture_code"
CONF_FIXTURES = "fixtures"
CONF_IMPORT_JSON = "import_json"
CONF_IMPORT_METHOD = "import_method"
CONF_IV_INDEX = "iv_index"
CONF_IMPORT_PATH = "import_path"
CONF_MESH_UUID = "mesh_uuid"
CONF_MODEL = "model"
CONF_NAME = "name"
CONF_NET_KEY = "net_key"
CONF_NODE_ADDRESS = "node_address"
CONF_PRODUCT_ID = "product_id"
CONF_PROXY_ADDRESS = "proxy_address"
CONF_PROXY_CANDIDATES = "proxy_candidates"
CONF_PROXY_MAC = "proxy_mac"
CONF_PROXY_SELECTION = "proxy_selection"
CONF_SEQUENCE = "sequence"
CONF_SELECTED_FIXTURE = "selected_fixture"
CONF_SELECTED_FIXTURE_IDS = "selected_fixture_ids"
CONF_SOURCE_ADDRESS = "source_address"
CONF_SUPPORTED_COLOR_MODES = "supported_color_modes"
CONF_SETUP_METHOD = "setup_method"
CONF_TTL = "ttl"
CONF_TRANSPORT_MODE = "transport_mode"

DEFAULT_IV_INDEX = 0
DEFAULT_NODE_ADDRESS = 2
DEFAULT_SEQUENCE = 100000
DEFAULT_SOURCE_ADDRESS = 0x000F
DEFAULT_TTL = 7
DEFAULT_ENABLE_DISCOVERY = False
DEFAULT_ENABLE_PRESENCE_CHECKING = False
DEFAULT_PRESENCE_UNAVAILABLE_AFTER_SECONDS = 120.0
DEFAULT_PRESENCE_SCAN_INTERVAL_SECONDS = 60.0
DEFAULT_PRESENCE_SCAN_DURATION_SECONDS = 10.0
TRANSPORT_MODE_TRANSIENT = "transient"
TRANSPORT_MODE_PERSISTENT = "persistent"
TRANSPORT_MODES = (TRANSPORT_MODE_TRANSIENT, TRANSPORT_MODE_PERSISTENT)
DEFAULT_TRANSPORT_MODE = TRANSPORT_MODE_TRANSIENT

PROXY_SELECTION_AUTO = "auto"
PROXY_SELECTION_MANUAL = "manual"
PROXY_SELECTIONS = (PROXY_SELECTION_AUTO, PROXY_SELECTION_MANUAL)
DEFAULT_PROXY_SELECTION = PROXY_SELECTION_MANUAL
DEFAULT_IMPORT_PROXY_SELECTION = PROXY_SELECTION_AUTO

MIN_COLOR_TEMP_KELVIN = 2300
MAX_COLOR_TEMP_KELVIN = 10000
DEFAULT_COLOR_TEMP_KELVIN = 5600

COLOR_MODE_COLOR_TEMP = "color_temp"
COLOR_MODE_HS = "hs"
COLOR_MODE_BRIGHTNESS = "brightness"

SETUP_METHOD_IMPORT = "import"
SETUP_METHOD_MANUAL = "manual"
SETUP_METHODS = (SETUP_METHOD_IMPORT, SETUP_METHOD_MANUAL)

IMPORT_METHOD_JSON = "paste_json"
IMPORT_METHOD_PATH = "local_path"
IMPORT_METHODS = (IMPORT_METHOD_JSON, IMPORT_METHOD_PATH)

TRANSPORT_STATE_DISCONNECTED = "disconnected"
TRANSPORT_STATE_WARMING = "warming"
TRANSPORT_STATE_PROXY_READY = "proxy_ready"
TRANSPORT_STATE_CONNECTED = "connected"
TRANSPORT_STATE_RECONNECTING = "reconnecting"
TRANSPORT_STATE_FAILED = "failed"
TRANSPORT_STATE_UNREACHABLE = "unreachable"

MESH_PROXY_IN_UUID = "00002add-0000-1000-8000-00805f9b34fb"
MESH_PROXY_OUT_UUID = "00002ade-0000-1000-8000-00805f9b34fb"

SIDUS_ACCESS_OPCODE = 0x26

SERVICE_REQUEST_POWER_STATUS = "request_power_status"
SERVICE_FIELD_ENTRY_ID = "entry_id"
SERVICE_FIELD_NODE_ADDRESS = "node_address"
SERVICE_FIELD_CAPTURE_SECONDS = "capture_seconds"
DEFAULT_POWER_STATUS_CAPTURE_SECONDS = 10.0
